package Tiimae.TiimaeBot.enums;

public enum ButtonEnum {
    ADDXPCHANNELBUTTON,
    ADDLOGCHANNELBUTTON,
    ADDWELCOMECHANNELBUTTON,
    ADDPREFIXBUTTON,
    ADDWELCOMEROLEBUTTON,
    ADDLEAVECHANNELBUTTON,
    ADDMEMBERCOUNTCHANNELBUTTON,
    ADDBOTCOUNTCHANNELBUTTON,
    ADDMUTEROLEBUTTON,
    UPDATEXPCHANNELBUTTON,
    UPDATELOGCHANNELBUTTON,
    UPDATEWELCOMECHANNELBUTTON,
    UPDATEPREFIXBUTTON,
    UPDATEWELCOMEROLEBUTTON,
    UPDATELEAVECHANNELBUTTON,
    UPDATEMEMBERCOUNTCHANNELBUTTON,
    UPDATEBOTCOUNTCHANNELBUTTON,
    UPDATEMUTEROLEBUTTON
}
