package Tiimae.TiimaeBot.enums;

public enum ButtonEnum {
    ADDXPCHANNELBUTTON,
    ADDLOGCHANNELBUTTON,
    ADDWELCOMECHANNELBUTTON,
    ADDPREFIXBUTTON,
    ADDWELCOMEROLEBUTTON,
    ADDLEAVECHANNELBUTTON,
    ADDMEMBERCOUNTCHANNELBUTTON,
    ADDBOTCOUNTCHANNELBUTTON,
    ADDMUTEROLEBUTTON
}
